### ISSUE TITLE
Impossible to change Profile number to 78

### ISSUE THREAD

**Issue by softclickbr** [BranchMetrics/xamarin-branch-deep-linking#41]
The actual .NET Framework 4.5 profile is 259, impossible to change it, impossible to use Xamarin Branch.

**Comment by antonargunov** [comment]
hi @softclickbr , sorry for delay,
quick solution:
- download source code of Xamarin SDK from our github
- add source code to your project (without Testbeds)
- create projects dependences
- set any profile you want

**Comment by softclickbr** [comment]
Thank you, but I'm not experienced to manual package install (i.e. I never hear about Testbeds)

**Comment by TheMarshal99** [comment]
Opportunities oopooooooopo

**Comment by TheMarshal99** [comment]
Ooioooooiioooooooiooo

**Comment by TheMarshal99** [comment]
Oooo

**Comment by TheMarshal99** [comment]
Oiooooiopuuoopooooop

**Comment by TheMarshal99** [comment]
Sorry, my phone must have opened up the notification email in my pocket!

**Comment by antonargunov** [comment]
@softclickbr sorry for delay, can you describe me what do you want to do?

I created cross-platform application for ios and android with using Xamarin Forms.
I added Branch SDK into ios and android projects (not into PCL project).
I can change my profile in my PCL project as I wish.

**Comment by RaFaGG** [comment]
@antonargunov if you create a cross-platform application for ios, android and UWP with using Xamarin Forms and you add Branch SDK into ios, android and PLC projects, the UWP don't compile (WP 8.1 compile). Problem of profile? The error is "Cannot resolve Assembly or Windows Metadata file 'Branch-Xamarin-SDK.dll'" Any help?

**Comment by antonargunov** [comment]
Hello @RaFaGG , sorry, but we don't support UWP.

**Comment by antonargunov** [comment]
@RaFaGG , important note, I DON'T add Branch SDK to PCL project.
I add Branch SDK into IOS and Android projects only.

You should have in one solution:
1) PCL project - for cross-platfrom code (business logic, deep linking processing etc.).
2) Android project - for native features (activities, GUI, initialization and working with Android implementation of Branch SDK, etc.)
3) IOS project - for native features (life cycle, GUI, initialization and working with IOS implementation of Branch SDK, etc.)

You can call deep linking processing methods of your PCL project from IOS and Android project.

**Comment by RaFaGG** [comment]
Hello again @antonargunov!  Sorry, there is something I am not understanding well. We follow the example of testbed and there the branch SDK in PCL is used to implement IBranchUrlInterface. In addition we create BranchUniversalObject to generate URL in PCL. Everything works fine on IOS and android. In wp 8.1 there are no problems for the app to work (obviously without the Branch functionality), but when compiling in UWP fails. We should implement IBranchUrlInterface, IBranchUrlInterface and BranchUniversalObject ... in Android and ios project?

**Comment by antonargunov** [comment]
Hello @RaFaGG , now I understood your issue.
Let me try that by myself.

**Comment by antonargunov** [comment]
@RaFaGG , several questions:
1) do you use Xamarin or MS VS?
2) did you add Branch SDK nuget package or Brach SDK source code?

**Comment by RaFaGG** [comment]
1. MS VS
2. Nuget package (version 3.0.3).
Thanks!

**Comment by antonargunov** [comment]
**Environment:**
1) Windows 10
2) MSVS 2015
    - Microsoft Visual Studio Community 2015 Version 14.0.25431.01 Update 3
    - Microsoft .NET Framework Version 4.6.01586
    - Nuget Package Manager Version 3.4.4.1321

**Created Solution:**
1) Blank App (Xamarin.Forms.Portable)
2) WindowPhone 8.1 was deleted from Targets In PCL project to change PCL profile 259 to PCL profile 78
  2.1) Uninstall Xamarin Forms package
  2.2) DeleteWindowPhone 8.1
  2.3) Install Xamarin Forms package

**Branch SDK package:**
1) Branch SDK added into PCL and UWP projects.
2) Creating of BranchUniversalObject was added into PCL and UWP projects

**Debug x86 Build log:**
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Rebuild All started: Project: App1, Configuration: Debug Any CPU ------
1>  App1 -> C:\VS_projects\App1\App1\App1\bin\Debug\App1.dll
2>------ Rebuild All started: Project: App1.UWP, Configuration: Debug x86 ------
2>C:\VS_projects\App1\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets(225,5): warning : All projects referencing App1.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
2>  App1.UWP -> C:\VS_projects\App1\App1\App1.UWP\bin\x86\Debug\App1.UWP.exe
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1930,5): warning APPX0108: The certificate specified has expired. For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Release x64 Build Log**
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Rebuild All started: Project: App1, Configuration: Release Any CPU ------
1>  App1 -> C:\VS_projects\App1\App1\App1\bin\Release\App1.dll
2>------ Rebuild All started: Project: App1.UWP, Configuration: Release x64 ------
2>C:\VS_projects\App1\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets(225,5): warning : All projects referencing App1.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
2>  App1.UWP -> C:\VS_projects\App1\App1\App1.UWP\bin\x64\Release\App1.UWP.exe
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1930,5): warning APPX0108: The certificate specified has expired. For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.
2>  Starting .NET Native compilation
2>  Processing application code
2>C:\VS_projects\App1\App1\App1.UWP\Resources.System.Linq.Expressions.rd.xml(35): warning : ILTransform_0027: Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.
2>C:\VS_projects\App1\App1\App1.UWP\Resources.System.Linq.Expressions.rd.xml(91): warning : ILTransform_0027: Method 'ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not be found.
2>  Computing application closure and generating interop code
2>  Generating serialization code
2>  Compiling interop code
2>  Cleaning up unreferenced code
2>  Generating native code
2>  Generating fixups for native code
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Note:** I didn't solve issues with Linq and certificate, because that was test for Branch SDK

**Comment by RaFaGG** [comment]
@antonargunov Thanks! In WP project not need no add Branch SDK but in UWP is necessary. All OK!

**Comment by antonargunov** [comment]
@RaFaGG Great!
Thanks for feedback!
So, I think issue is solved.
