### ISSUE TITLE
Xamarin.iOS, link click takes to Appstore instead of the app (already installed)

### ISSUE THREAD

**Issue by venky284** [BranchMetrics/xamarin-branch-deep-linking#47]
Hi

Followed all the steps in the integration process. Used to work fine. Suddenly we observed that the click on Branch Links takes to Appstore instead of the app (already installed).

Any specific reason that it happens?

**Comment by antonargunov** [comment]
HI @venky284 ,
what link do you use:
- created in dashboard
- generated in your app
?

**Comment by agrimn** [comment]
Hi @venky284 ,

I just ran a quick test with the live link: https://ready.app.link/8Mb8m5CWlA on your Dashboard and I saw the link route me to your production app (App that I downloaded from the App Store).

Can you please make sure that you have not disabled Universal links for your app on your device?

To re-enable Universal Links, long press on the link in Messages (iOS 9 only due to iMessage revamp in 10) or Notes (iOS 10/9) and choose ‘Open in «App»’.

If you continue having issues with links routing into your app can you please write into integrations@branch.io with the links that you are using to test.

**Comment by venky284** [comment]
Hi @antonargunov 

They are dynamically created (not generated in the app though)

https://<<LINK_DOMAIN>>.app.link?<<CUSTOM_PARAMS>
https://bnc.lt/a/<<KEY_LIVE>>?<<CUSTOM_PARAMS>>

@agrimn , Sure. Will write to integrations@branch.io

**Comment by venky284** [comment]
@antonargunov , After going through trouble shooting guide, realised that we missed to add 'branch_app_domain' in Info.plist file ('branch_key' is already included).

When we click on bnc.lt links, redirects to Appstore. However, clicking on app.link links, directs to the app.

Would like to clarify if we enable Link_domain, legacy bnc.lt links won't work as universal links?

**Comment by antonargunov** [comment]
@venky284 , try to add your bnc.lt links to "associated domains" like you did for app.link links.
